name = "telegraph-image"
compatibility_date = "2026-02-28"
pages_build_output_dir = "."

[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "telegraph-image-files"

[[d1_databases]]
binding = "DB"
database_name = "telegraph_image"
database_id = "5c4e4696-4a83-41dd-80a4-ff58b7c73349"

[[kv_namespaces]]
binding = "img_url"
id = "5d47a06d84d54b5cb74425d02d4a3a5b"
